# Generated by Django 2.2.8 on 2019-12-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pin',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
