# Generated by Django 2.2.8 on 2019-12-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_message_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pin',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
