# Generated by Django 2.2.8 on 2019-12-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191230_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
