# Generated by Django 2.2.8 on 2019-12-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191230_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='pin',
            new_name='password',
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='Abcd', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
