# Generated by Django 2.2.8 on 2019-12-30 10:55

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191230_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='yes_no',
            field=models.CharField(blank=True, choices=[('y', 'yes'), ('n', 'no')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_image_path),
        ),
    ]
