# Generated by Django 2.2.8 on 2019-12-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191230_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='yes_no',
        ),
    ]
